server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    #应用的名称，可选
    name: orrengelive
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver  # MySQL 5.5 使用旧驱动类
      url: jdbc:mysql://localhost:3306/orangelife?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#reggie:
#  path: D:\img\

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true